# Generated by Django 4.0.4 on 2022-05-31 19:00

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apenom', models.CharField(max_length=50, verbose_name='Apellido y Nombre')),
                ('fechaNac', models.DateField(blank=True, null=True, verbose_name='Fecha de Nacimiento')),
                ('fechaDeceso', models.DateField(blank=True, null=True)),
                ('imagen', models.ImageField(null=True, upload_to='autores')),
            ],
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Idioma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('resumen', models.TextField(help_text='Ingrese el resumen del libro...', max_length=1000)),
                ('imagen', models.ImageField(null=True, upload_to='img')),
                ('autor', models.ForeignKey(help_text='Ingrese el autor (es uno solo)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogo.autor')),
                ('genero', models.ManyToManyField(help_text='Seleccione un genero(o varios) para este libro...', to='catalogo.genero')),
                ('idioma', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogo.idioma')),
            ],
        ),
        migrations.CreateModel(
            name='Ejemplar',
            fields=[
                ('uniqueId', models.UUIDField(default=uuid.uuid4, help_text='ID unico para este libro particular en toda la biblioteca...', primary_key=True, serialize=False)),
                ('ISBN', models.CharField(blank=True, help_text='Ingrese 13 digitos de la forma: XXX-XX-XXXXX-XX-X, para mas ayuda ingresar a <a href="https://www.isbn-international.org/es/content/%C2%BFqu%C3%A9-es-un-isbn" target="_blanck">Ayuda sobre el numero ISBN</a>', max_length=17, unique=True, validators=[django.core.validators.RegexValidator('\\d{3}-\\d{2}-\\d{5}-\\d{2}-\\d')])),
                ('fechaDevolucion', models.DateField(blank=True, null=True, verbose_name='Fecha de Devolución')),
                ('estado', models.CharField(blank=True, choices=[('m', 'en Mantenimiento'), ('p', 'Prestado'), ('d', 'Disponible'), ('r', 'Reservado')], default='d', help_text='Ingrese Disponibilidad del ejemplar...', max_length=1)),
                ('libro', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogo.libro')),
            ],
            options={
                'ordering': ['fechaDevolucion'],
            },
        ),
    ]
