# Generated by Django 4.0.4 on 2022-05-31 19:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ejemplar',
            name='ISBN',
            field=models.CharField(blank=True, help_text='Ingrese 13 digitos de la forma: XXX-XX-XXXXX-XX-X, para mas ayuda ingresar a <a href="https://www.isbn-international.org/es/content/%C2%BFqu%C3%A9-es-un-isbn" target="_blanck">Ayuda sobre el numero ISBN</a>', max_length=17, validators=[django.core.validators.RegexValidator('\\d{3}-\\d{2}-\\d{5}-\\d{2}-\\d')]),
        ),
    ]
