# Generated by Django 4.0.4 on 2022-06-07 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_alter_ejemplar_isbn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autor',
            name='fechaDeceso',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Deceso'),
        ),
        migrations.AlterField(
            model_name='genero',
            name='nombre',
            field=models.CharField(help_text='Ingrese el nombre del nuevo Genero (por ejemplo. Programacion, BD, SO, etc.)', max_length=60),
        ),
    ]
