# Generated by Django 4.0.4 on 2022-06-08 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0003_alter_autor_fechadeceso_alter_genero_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autor',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='autores'),
        ),
    ]
