# Generated by Django 4.0.4 on 2022-06-11 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0004_alter_autor_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autor',
            name='imagen',
            field=models.ImageField(default='autores/noposee_foto.png', null=True, upload_to='autores'),
        ),
        migrations.AlterField(
            model_name='idioma',
            name='nombre',
            field=models.CharField(help_text='Ingrese el nuevo Idioma (por ejemplo. Ingles, Español, etc.)', max_length=25),
        ),
    ]
