# Generated by Django 4.0.4 on 2022-06-14 20:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0005_alter_autor_imagen_alter_idioma_nombre'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ejemplar',
            options={'ordering': ['libro']},
        ),
        migrations.AlterField(
            model_name='ejemplar',
            name='ISBN',
            field=models.CharField(help_text='Ingrese 13 digitos de la forma: XXX-XX-XXXXX-XX-X, para mas ayuda ingresar a <a href="https://www.isbn-international.org/es/content/%C2%BFqu%C3%A9-es-un-isbn" target="_blanck">Ayuda sobre el numero ISBN</a>', max_length=17, unique=True, validators=[django.core.validators.RegexValidator('\\d{3}-\\d{2}-\\d{5}-\\d{2}-\\d')]),
        ),
        migrations.AlterField(
            model_name='ejemplar',
            name='estado',
            field=models.CharField(choices=[('m', 'en Mantenimiento'), ('p', 'Prestado'), ('d', 'Disponible'), ('r', 'Reservado')], default='d', help_text='Ingrese Disponibilidad del ejemplar...', max_length=1),
        ),
        migrations.AlterField(
            model_name='libro',
            name='imagen',
            field=models.ImageField(default='portada/noposee_portada.png', null=True, upload_to='portada'),
        ),
    ]
