# Generated by Django 4.0.4 on 2022-06-24 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0007_poi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poi',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='poi',
            name='lng',
        ),
        migrations.AddField(
            model_name='poi',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='poi',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
