# Generated by Django 4.0.4 on 2022-06-25 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0008_remove_poi_lat_remove_poi_lng_poi_latitude_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poi',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='poi',
            name='longitude',
        ),
    ]
