# Generated by Django 4.0.4 on 2022-06-25 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0009_remove_poi_latitude_remove_poi_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='poi',
            name='lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='poi',
            name='lng',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
