# Generated by Django 4.0.4 on 2022-06-25 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0010_poi_lat_poi_lng'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autor',
            name='imagen',
            field=models.ImageField(default='img/noposee_foto.png', null=True, upload_to='autores'),
        ),
        migrations.AlterField(
            model_name='libro',
            name='imagen',
            field=models.ImageField(default='img/noposee_portada.png', null=True, upload_to='portada'),
        ),
    ]
