# Generated by Django 4.0.4 on 2022-06-25 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0011_alter_autor_imagen_alter_libro_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autor',
            name='fechaNac',
            field=models.DateField(null=True, verbose_name='Fecha de Nacimiento'),
        ),
        migrations.AlterField(
            model_name='libro',
            name='imagen',
            field=models.ImageField(default='img/noposee_portada.png', null=True, upload_to='portadas'),
        ),
    ]
