# Generated by Django 4.0.4 on 2022-06-25 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0012_alter_autor_fechanac_alter_libro_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='imagen',
            field=models.ImageField(default='img/noposee_portada.png', null=True, upload_to='autores'),
        ),
    ]
