# Generated by Django 4.0.4 on 2022-07-07 23:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalogo', '0013_alter_libro_imagen'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='autor',
            options={'ordering': ['apenom']},
        ),
        migrations.AlterModelOptions(
            name='genero',
            options={'ordering': ['nombre']},
        ),
        migrations.AlterModelOptions(
            name='libro',
            options={'ordering': ['titulo']},
        ),
        migrations.AlterField(
            model_name='libro',
            name='imagen',
            field=models.ImageField(default='img/noposee_portada.png', null=True, upload_to='portadas'),
        ),
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poi', models.ForeignKey(help_text='Ingrese direccion', null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogo.poi')),
                ('usuario', models.ForeignKey(help_text='Ingrese el usuario', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
